name: "Nível 3: Containers e Segurança"

on:
  pull_request:
    types: [closed]
    branches: [ desafio-nivel-3 ]

permissions:
  contents: read
  packages: write

env:
  CHALLENGE_LEVEL: 3
  CHALLENGE_NAME: "guto-containers-e-seguranca"
  REGISTRY: ghcr.io

jobs:
  build-scan-and-push:
    name: "Build, Lint, Trivy Scan e Push no GHCR"
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout do código"
        uses: actions/checkout@v5

      # DESAFIO 3 - hadolint - Falhar caso detecte as regras DL3006 e DL3008
      - name: "Lint do Dockerfile com Hadolint"
        run: |
          docker run --rm -i hadolint/hadolint < Dockerfile > lint-report.txt || true
          if grep -q 'DL3006' lint-report.txt; then
            echo "Erro: Regra DL3006 violada."
            exit 1
          fi
          if grep -q 'DL3008' lint-report.txt; then
            echo "Erro: Regra DL3008 violada."
            exit 1
          fi
      - name: "Upload do relatório do Hadolint"
        uses: actions/upload-artifact@v4
        with:
          name: lint-report.txt
          path: lint-report.txt

      # DESAFIO 3 - OBRIGARÓRIO
      - name: "Login no GitHub Container Registry (GHCR)"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build da imagem Docker (sem push ainda)
      - name: "Build da imagem Docker"
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.CHALLENGE_NAME }}:${{ github.sha }}
          load: true

      # Scan de vulnerabilidades com Trivy
      - name: "Scan de vulnerabilidades com Trivy"
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.CHALLENGE_NAME }}:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
          ignore-unfixed: true
          vuln-type: 'os,library'
          output: 'trivy-report.txt'
          scan-type: 'image'

      - name: "Upload do relatório de vulnerabilidades"
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report.txt
          path: trivy-report.txt

      # Push da imagem só se tudo passou
      - name: "Push da imagem para o GHCR"
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.CHALLENGE_NAME }}:${{ github.sha }}
          load: false

  generate-certificate: # DAQUI PARA BAIXO, NÃO ALTERAR
    name: "Desafio Nível 3 - Certificado"
    needs: build-scan-and-push
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: "Gerar certificado"
        run: |
          mkdir -p certificates
          cat > certificates/level-3-certificate.md << EOF
          # Certificado de Conclusão - Nível 3

          **Descomplicando Github Actions - GitHub Actions Edition**
          ---

          Este certificado atesta que **${{ github.actor }}** concluiu com sucesso:
          ## Nível 3: Containers e Segurança

          **Competências desenvolvidas:**
          - Build de imagem Docker
          - Lint de Dockerfile com Hadolint
          - Scan de vulnerabilidades com Trivy (CRITICAL = 0)
          - Relatório de vulnerabilidades como artefato
          - Smoke test de execução do container
          - Publicação no GitHub Container Registry (GHCR) condicionada ao scan
          - Boas práticas de supply chain

          **Data de conclusão:** $(date)
          **Repositório:** ${{ github.repository }}
          **Workflow:** ${{ github.run_id }}

          ---
          **Badge conquistado:** Containers e Segurança

          ---
          *Certificado gerado automaticamente pelo GitHub Actions*
          *LINUXtips*
          EOF

      - name: "Upload do certificado"
        uses: actions/upload-artifact@v4
        with:
          name: level-3-certificate
          path: certificates/
          retention-days: 30
